#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Take down the S6 supervision tree when the process fails

if [[ "${1}" -ne 0 && "${1}" -ne 256 ]]; then
  exec s6-svscanctl -t /var/run/s6/services
fi
