#!/command/with-contenv bash
# shellcheck shell=bash
# Start the go2rtc service

# Replace the bash process with the go2rtc process, redirecting stderr to stdout
exec 2>&1
exec go2rtc -config=/dev/shm/go2rtc.yaml
