#!/command/with-contenv bash
# shellcheck shell=bash

# https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425?permalink_comment_id=3945021
set -euo pipefail

if [[ -f "/config/frigate-go2rtc.yaml" ]]; then
    config_path="/config/frigate-go2rtc.yaml"
else
    config_path="/usr/local/go2rtc/go2rtc.yaml"
fi

exec 2>&1
exec go2rtc -config="${config_path}"
