#!/usr/bin/python3
# -*- coding: utf-8 -*-s
__import__("pysqlite3")

import re
import sys

sys.modules["sqlite3"] = sys.modules.pop("pysqlite3")

from chromadb.cli.cli import app

if __name__ == "__main__":
    sys.argv[0] = re.sub(r"(-script\.pyw|\.exe)?$", "", sys.argv[0])
    sys.exit(app())
