module["exports"] = [
  "de la Banque",
  "de la Barbe",
  "de Barchon",
  "Baron Horta",
  "aux Barques",
  "des Barricades",
  "Barthélémy",
  "du Baudet",
  "Frédéric Basse",
  "du Béguinage",
  "de Berlaimont",
  "au Beurre",
  "Henri Beyaert",
  "de Bischoffsheim",
  "Blaes",
  "de la Blanchisserie",
  "des Blindés",
  "de la Bobine",
  "Bodeghem",
  "Bodenbroeck",
  "des Boeufs",
  "des Bogards",
  "du Bois à Brûler",
  "au Bois de Construction",
  "du Bois Sauvage",
  "des Boîteux",
  "de Bon Secours",
  "du Borgendael",
  "Borgval",
  "Bortier",
  "des Bouchers",
  "rue des Bouchers",
  "du Boulet",
  "de la Bouquetière",
  "de la Bourse",
  "de la Braie",
  "des Brasseurs",
  "Brederode",
  "Jacques Brel",
  "Breughel",
  "des Brigittines",
  "rue des Brigittines",
  "aux Briques",
  "des Brodeurs",
  "de la Buanderie",
  "Charles Buls",
  "des Cadeaux",
  "Camusel",
  "du Canal",
  "du Canon",
  "Cantersteen",
  "des Capucins",
  "Cardinal Mercier",
  "de la Caserne",
  "des Cendres",
  "du Centre",
  "Chair et Pain",
  "des Chaisiers",
  "de la Chancellerie",
  "des Chandeliers",
  "du Chantier",
  "du Chapelet",
  "des Chapeliers",
  "de la Chapelle",
  "du Char",
  "des Charpentiers",
  "des Chartreux",
  "du Chasseur",
  "de la Chaufferette",
  "à la Chaux",
  "du Chêne",
  "du Cheval",
  "du Chevreuil",
  "du Chien Marin",
  "aux Choux",
  "Christine",
  "de la Cigogne",
  "du Cirque",
  "de la Clé",
  "de la Collégiale",
  "de la Colline",
  "du Colombier",
  "des Colonies",
  "des Comédiens",
  "des Commerçants",
  "du Commerce",
  "du Congrès",
  "Coppens",
  "Coudenberg",
  "Jo Cox",
  "de la Croix de Fer",
  "Cuerens",
  "des Cultes",
  "de Cureghem",
  "de la Cuve",
  "du Cyprès",
  "des Echelles",
  "de l' Eclipse",
  "de l' Economie",
  "de l' Ecuyer",
  "d' Egmont",
  "de l' Empereur",
  "de l' Enseignement",
  "de l' Epargne",
  "de l' Epée",
  "des Eperonniers",
  "de l' Escalier",
  "des Escrimeurs",
  "d' Espagne",
  "de l' Etuve",
  "de l' Europe",
  "de l' Eventail",
  "de l' Evêque",
  "Evers",
  "des Fabriques",
  "des Faisans",
  "de la Faucille",
  "du Faucon",
  "de la Ferraille",
  "de la Fiancée",
  "de la Fidélité",
  "du Finistère",
  "de Flandre",
  "des Fleuristes",
  "aux Fleurs",
  "au Foin",
  "Fontainas",
  "de la Fontaine",
  "de la Forêt d'Houthulst",
  "Fossé-aux-Loups",
  "des Foulons",
  "de la Fourche",
  "des Fripiers",
  "Froebel",
  "blanche",
  "noire",
  "verte",
  "pont de bois",
  "grand poire",
  "du marché",
  "du lundi",
  "des médias",
  "Robert Schuman",
  "du papier plié",
  "de la croix de fer",
  "cronque",
  "de l'Abbaye",
  "Adolphe Mille",
  "d'Assas",
  "du Bac",
  "de Paris",
  "La Boétie",
  "du roi",
  "de la Bûcherie",
  "de Caumartin",
  "Charlemagne",
  "du Chat-qui-Pêche",
  "de la Chaussée-d'Antin",
  "du Dahomey",
  "Dauphine",
  "Delesseux",
  "du Faubourg Saint-Honoré",
  "du Faubourg-Saint-Denis",
  "de la Ferronnerie",
  "des Francs-Bourgeois",
  "des Grands Augustins",
  "de la Harpe",
  "du Havre",
  "de la Huchette",
  "Joubert",
  "Laffitte",
  "Lepic",
  "des Lombards",
  "Marcadet",
  "Molière",
  "Monsieur-le-Prince",
  "de Montmorency",
  "Montorgueil",
  "Mouffetard",
  "de Nesle",
  "Oberkampf",
  "de l'Odéon",
  "d'Orsel",
  "de la Paix",
  "des Panoramas",
  "Pastourelle",
  "Pierre Charron",
  "de la Pompe",
  "de Presbourg",
  "de Provence",
  "de Richelieu",
  "de Rivoli",
  "des Rosiers",
  "Royale",
  "d'Abbeville",
  "Saint-Honoré",
  "Saint-Bernard",
  "Saint-Denis",
  "Saint-Dominique",
  "Saint-Jacques",
  "Saint-Séverin",
  "des Saussaies",
  "de Seine",
  "de Solférino",
  "Du Sommerard",
  "de Tilsitt",
  "Vaneau",
  "de Vaugirard",
  "de la Victoire",
  "Zadkine"
];
