title: "[Detector Support]: "
labels: ["support", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Use this form for support or questions related to Frigate's object detectors.

        Before submitting your support request, please [search the discussions][discussions], read the [official Frigate documentation][docs], and read the [Frigate FAQ][faq] pinned at the Discussion page to see if your question has already been answered by the community.

        [discussions]: https://www.github.com/blakeblackshear/frigate/discussions
        [docs]: https://docs.frigate.video
        [faq]: https://github.com/blakeblackshear/frigate/discussions/12724
  - type: textarea
    id: description
    attributes:
      label: Describe the problem you are having
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Visible on the System page in the Web UI. Please include the full version including the build identifier (eg. 0.14.0-ea36ds1)
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Frigate config file
      description: This will be automatically formatted into code, so no need for backticks.
      render: yaml
    validations:
      required: true
  - type: textarea
    id: docker
    attributes:
      label: docker-compose file or Docker CLI command
      description: This will be automatically formatted into code, so no need for backticks.
      render: yaml
    validations:
      required: true
  - type: textarea
    id: frigatelogs
    attributes:
      label: Relevant Frigate log output
      description: Please copy and paste any relevant Frigate log output. Include logs before and after your exact error when possible. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: textarea
    id: go2rtclogs
    attributes:
      label: Relevant go2rtc log output
      description: Please copy and paste any relevant go2rtc log output. Include logs before and after your exact error when possible. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - HassOS
        - Debian
        - Other Linux
        - Proxmox
        - UNRAID
        - Windows
        - Other
    validations:
      required: true
  - type: dropdown
    id: install-method
    attributes:
      label: Install method
      options:
        - HassOS Addon
        - Docker Compose
        - Docker CLI
    validations:
      required: true
  - type: dropdown
    id: object-detector
    attributes:
      label: Object Detector
      options:
        - Coral
        - OpenVino
        - TensorRT
        - RKNN
        - Other
        - CPU (no coral)
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots of the Frigate UI's System metrics pages and any other screenshots pertinent to your issue.
      description: Drag and drop for images is possible in this field.
  - type: textarea
    id: other
    attributes:
      label: Any other information that may be helpful
