title: "[Support]: "
labels: ["support", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Use this form for support for issues that don't fall into any specific category.

        Before submitting your support request, please [search the discussions][discussions], read the [official Frigate documentation][docs], and read the [Frigate FAQ][faq] pinned at the Discussion page to see if your question has already been answered by the community.

        [discussions]: https://www.github.com/blakeblackshear/frigate/discussions
        [docs]: https://docs.frigate.video
        [faq]: https://github.com/blakeblackshear/frigate/discussions/12724
  - type: textarea
    id: description
    attributes:
      label: Describe the problem you are having
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Visible on the System page in the Web UI. Please include the full version including the build identifier (eg. 0.14.0-ea36ds1)
    validations:
      required: true
  - type: input
    attributes:
      label: What browser(s) are you using?
      placeholder: Google Chrome 88.0.4324.150
      description: >
        Provide the full name and don't forget to add the version!
  - type: textarea
    id: config
    attributes:
      label: Frigate config file
      description: This will be automatically formatted into code, so no need for backticks.
      render: yaml
    validations:
      required: true
  - type: textarea
    id: frigatelogs
    attributes:
      label: Relevant Frigate log output
      description: Please copy and paste any relevant Frigate log output. Include logs before and after your exact error when possible. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: textarea
    id: go2rtclogs
    attributes:
      label: Relevant go2rtc log output
      description: Please copy and paste any relevant go2rtc log output. Include logs before and after your exact error when possible. Logs can be viewed via the Frigate UI, Docker, or the go2rtc dashboard. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: textarea
    id: ffprobe
    attributes:
      label: FFprobe output from your camera
      description: Run `ffprobe <camera_url>` from within the Frigate container if possible, and provide output below
      render: shell
    validations:
      required: true
  - type: textarea
    id: stats
    attributes:
      label: Frigate stats
      description: Output from frigate's /api/stats endpoint
      render: json
  - type: dropdown
    id: install-method
    attributes:
      label: Install method
      options:
        - HassOS Addon
        - Docker Compose
        - Docker CLI
        - Proxmox via Docker
        - Proxmox via TTeck Script
        - Windows WSL2
    validations:
      required: true
  - type: textarea
    id: docker
    attributes:
      label: docker-compose file or Docker CLI command
      description: This will be automatically formatted into code, so no need for backticks.
      render: yaml
    validations:
      required: true
  - type: dropdown
    id: object-detector
    attributes:
      label: Object Detector
      options:
        - Coral
        - OpenVino
        - TensorRT
        - RKNN
        - Other
        - CPU (no coral)
    validations:
      required: true
  - type: dropdown
    id: network
    attributes:
      label: Network connection
      options:
        - Wired
        - Wireless
        - Mixed
    validations:
      required: true
  - type: input
    id: camera
    attributes:
      label: Camera make and model
      description: Dahua, hikvision, amcrest, reolink, etc and model number
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots of the Frigate UI's System metrics pages
      description: Drag and drop for images is possible in this field
  - type: textarea
    id: other
    attributes:
      label: Any other information that may be helpful
