title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Use this form for questions you have about Frigate.

        Before submitting your question, please [search the discussions][discussions], read the [official Frigate documentation][docs], and read the [Frigate FAQ][faq] pinned at the Discussion page to see if your question has already been answered by the community.

        **If you are looking for support, start a new discussion and use a support category.**

        [discussions]: https://www.github.com/blakeblackshear/frigate/discussions
        [docs]: https://docs.frigate.video
        [faq]: https://github.com/blakeblackshear/frigate/discussions/12724
  - type: textarea
    id: description
    attributes:
      label: "What is your question?"
    validations:
      required: true
