declare const _exports: {
    (text: TemplateStringsArray, ...placeholders: unknown[]): string;
    (...text: unknown[]): string;
    Instance: chalk.Instance;
    level: chalk.Level;
    hex(color: string): chalk.Chalk;
    keyword(color: string): chalk.Chalk;
    rgb(red: number, green: number, blue: number): chalk.Chalk;
    hsl(hue: number, saturation: number, lightness: number): chalk.Chalk;
    hsv(hue: number, saturation: number, value: number): chalk.Chalk;
    hwb(hue: number, whiteness: number, blackness: number): chalk.Chalk;
    ansi(code: number): chalk.Chalk;
    ansi256(index: number): chalk.Chalk;
    bgHex(color: string): chalk.Chalk;
    bgKeyword(color: string): chalk.Chalk;
    bgRgb(red: number, green: number, blue: number): chalk.Chalk;
    bgHsl(hue: number, saturation: number, lightness: number): chalk.Chalk;
    bgHsv(hue: number, saturation: number, value: number): chalk.Chalk;
    bgHwb(hue: number, whiteness: number, blackness: number): chalk.Chalk;
    bgAnsi(code: number): chalk.Chalk;
    bgAnsi256(index: number): chalk.Chalk;
    readonly reset: chalk.Chalk;
    readonly bold: chalk.Chalk;
    readonly dim: chalk.Chalk;
    readonly italic: chalk.Chalk;
    readonly underline: chalk.Chalk;
    readonly inverse: chalk.Chalk;
    readonly hidden: chalk.Chalk;
    readonly strikethrough: chalk.Chalk;
    readonly visible: chalk.Chalk;
    readonly black: chalk.Chalk;
    readonly red: chalk.Chalk;
    readonly green: chalk.Chalk;
    readonly yellow: chalk.Chalk;
    readonly blue: chalk.Chalk;
    readonly magenta: chalk.Chalk;
    readonly cyan: chalk.Chalk;
    readonly white: chalk.Chalk;
    readonly gray: chalk.Chalk;
    readonly grey: chalk.Chalk;
    readonly blackBright: chalk.Chalk;
    readonly redBright: chalk.Chalk;
    readonly greenBright: chalk.Chalk;
    readonly yellowBright: chalk.Chalk;
    readonly blueBright: chalk.Chalk;
    readonly magentaBright: chalk.Chalk;
    readonly cyanBright: chalk.Chalk;
    readonly whiteBright: chalk.Chalk;
    readonly bgBlack: chalk.Chalk;
    readonly bgRed: chalk.Chalk;
    readonly bgGreen: chalk.Chalk;
    readonly bgYellow: chalk.Chalk;
    readonly bgBlue: chalk.Chalk;
    readonly bgMagenta: chalk.Chalk;
    readonly bgCyan: chalk.Chalk;
    readonly bgWhite: chalk.Chalk;
    readonly bgGray: chalk.Chalk;
    readonly bgGrey: chalk.Chalk;
    readonly bgBlackBright: chalk.Chalk;
    readonly bgRedBright: chalk.Chalk;
    readonly bgGreenBright: chalk.Chalk;
    readonly bgYellowBright: chalk.Chalk;
    readonly bgBlueBright: chalk.Chalk;
    readonly bgMagentaBright: chalk.Chalk;
    readonly bgCyanBright: chalk.Chalk;
    readonly bgWhiteBright: chalk.Chalk;
};
export = _exports;
import chalk = require("chalk");
//# sourceMappingURL=chalk.d.ts.map