#!/command/with-contenv bash
# shellcheck shell=bash
# Download yolov8 models when DOWNLOAD_YOLOV8=1 environment variable is set

set -o errexit -o nounset -o pipefail

python3 /opt/frigate/frigate/util/download_models.py

