name: "Bug Report"
description: "Submit a specific UI or backend bug report."
blank_issues_enabled: false
contact_links:
  - name: Frigate Bug Report
    url: https://github.com/blakeblackshear/frigate/discussions/new/choose
    about: Report a specific bug.
