#!/usr/bin/with-contenv bash

PUID=${PUID:-1000}
PGID=${PGID:-1000}

groupmod -o -g "$PGID" frigate
usermod -o -u "$PUID" frigate

chown -R frigate:frigate /opt/frigate/frigate
chown -R frigate:frigate /opt/frigate/migrations
chown -R frigate:frigate /opt/frigate/web
chown -R frigate:frigate /usr/local/nginx
