#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/workspace/frigate/web/node_modules/.pnpm/typescript@5.9.2/node_modules/typescript/bin/node_modules:/workspace/frigate/web/node_modules/.pnpm/typescript@5.9.2/node_modules/typescript/node_modules:/workspace/frigate/web/node_modules/.pnpm/typescript@5.9.2/node_modules:/workspace/frigate/web/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/workspace/frigate/web/node_modules/.pnpm/typescript@5.9.2/node_modules/typescript/bin/node_modules:/workspace/frigate/web/node_modules/.pnpm/typescript@5.9.2/node_modules/typescript/node_modules:/workspace/frigate/web/node_modules/.pnpm/typescript@5.9.2/node_modules:/workspace/frigate/web/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../typescript@5.9.2/node_modules/typescript/bin/tsc" "$@"
else
  exec node  "$basedir/../../../../../typescript@5.9.2/node_modules/typescript/bin/tsc" "$@"
fi
