#!/command/with-contenv bash
# shellcheck shell=bash
# Compile YoloV8 ONNX files into ROCm MIGraphX files

for onnx in /config/model_cache/yolov8/*.onnx
do
  mxr="${onnx%.onnx}.mxr"
  if ! test -f $mxr; then
    echo "processing $onnx into $mxr"
    /opt/rocm/bin/migraphx-driver compile $onnx --optimize --gpu --enable-offload-copy --binary -o $mxr
  fi
done

