#!/command/with-contenv bash
# shellcheck shell=bash
# Prepare the logs folder for s6-log

set -o errexit -o nounset -o pipefail

dirs=(/dev/shm/logs/frigate /dev/shm/logs/go2rtc /dev/shm/logs/nginx /dev/shm/logs/certsync)

mkdir -p "${dirs[@]}"
if [ "$(id -u)" = "0" ]; then
    chown nobody:nogroup "${dirs[@]}"
fi
chmod 02755 "${dirs[@]}"
