#!/command/with-contenv bash
# shellcheck shell=bash

set -o errexit -o nounset -o pipefail

readonly exit_code_service="${1}"
readonly exit_code_signal="${2}"
readonly service="go2rtc-healthcheck"

echo "[INFO] The ${service} service exited with code ${exit_code_service} (by signal ${exit_code_signal})" >&2
