#!/command/with-contenv bash
# shellcheck shell=bash
# Start the go2rtc healthcheck service

set -o errexit -o nounset -o pipefail

echo "[INFO] Starting go2rtc healthcheck service..." >&2

while sleep 1m; do
    # Check if the service is running
    if ! curl -fsSL http://127.0.0.1:1984/api/streams >/dev/null; then
        echo "[ERROR] The go2rtc is apparently not working, restarting it..." >&2
        # We can also use -r instead of -t to send kill signal rather than term
        s6-svc -t /var/run/service/go2rtc
    fi
done
