#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/workspace/frigate/web/node_modules/.pnpm/msw@2.11.3_@types+node@20.19.17_typescript@5.9.2/node_modules/msw/cli/node_modules:/workspace/frigate/web/node_modules/.pnpm/msw@2.11.3_@types+node@20.19.17_typescript@5.9.2/node_modules/msw/node_modules:/workspace/frigate/web/node_modules/.pnpm/msw@2.11.3_@types+node@20.19.17_typescript@5.9.2/node_modules:/workspace/frigate/web/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/workspace/frigate/web/node_modules/.pnpm/msw@2.11.3_@types+node@20.19.17_typescript@5.9.2/node_modules/msw/cli/node_modules:/workspace/frigate/web/node_modules/.pnpm/msw@2.11.3_@types+node@20.19.17_typescript@5.9.2/node_modules/msw/node_modules:/workspace/frigate/web/node_modules/.pnpm/msw@2.11.3_@types+node@20.19.17_typescript@5.9.2/node_modules:/workspace/frigate/web/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../cli/index.js" "$@"
else
  exec node  "$basedir/../../cli/index.js" "$@"
fi
