# Table of Contents

* [Getting Started](start.md)
* [Shell API](api/Shell/README.md)
  * [initialize](api/Shell/initialize.md)
  * [addCommand](api/Shell/addCommand.md)
  * [addArgument](api/Shell/addArgument.md)
  * [addParameter](api/Shell/addParameter.md)
  * [addParameters](api/Shell/addParameters.md)
  * [clear](api/Shell/clear.md)
  * [invoke](api/Shell/invoke.md)
  * [dispose](api/Shell/dispose.md)
  * [properties](api/Shell/properties.md)
  * [events](api/Shell/events.md)
* [PSCommand API](api/PSCommand/README.md)
  * [initialize](api/PSCommand/initialize.md)
  * [addArgument](api/PSCommand/addArgument.md)
  * [addParameter](api/PSCommand/addParameter.md)
  * [clone](api/PSCommand/clone.md)
* [Tips](tips.md)
* [Change Log](../CHANGELOG.md)
* [PowerShell 6](https://docs.microsoft.com/en-us/powershell/scripting/powershell-scripting?view=powershell-6)