name: Maintain Cache

on:
  schedule:
    - cron: "13 0 * * 0,4"

env:
  PYTHON_VERSION: 3.9

jobs:
  multi_arch_build:
    runs-on: ubuntu-latest
    name: Image Build
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up QEMU and Buildx
        uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64
          target: frigate
          cache-from: type=gha
